"""add scrape run and log tables

Revision ID: 86511a487ec0
Revises: f764af9de14d
Create Date: 2026-06-14 20:38:19.335898

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86511a487ec0"
down_revision: str | Sequence[str] | None = "f764af9de14d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("new_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("removed_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["dealers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scrape_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_scrape_runs_dealer_id_started_at", ["dealer_id", "started_at"], unique=False
        )

    op.create_table(
        "scrape_log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scrape_run_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("old_price", sa.Integer(), nullable=True),
        sa.Column("new_price", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["car_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scrape_run_id"],
            ["scrape_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scrape_log_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_scrape_log_entries_scrape_run_id", ["scrape_run_id"], unique=False
        )

    with op.batch_alter_table("dealers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_scraped_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dealers", schema=None) as batch_op:
        batch_op.drop_column("last_scraped_at")

    with op.batch_alter_table("scrape_log_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_scrape_log_entries_scrape_run_id")

    op.drop_table("scrape_log_entries")
    with op.batch_alter_table("scrape_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_scrape_runs_dealer_id_started_at")

    op.drop_table("scrape_runs")
    # ### end Alembic commands ###
