"""create core tables

Revision ID: f764af9de14d
Revises:
Create Date: 2026-06-14 15:23:07.076638

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f764af9de14d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dealers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("scraper_module", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scraper_module"),
    )
    op.create_table(
        "tracked_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("variant", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "make", "model", "variant", name="uq_tracked_models_make_model_variant"
        ),
    )
    op.create_table(
        "car_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("variant", sa.String(length=100), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("fuel_type", sa.String(length=50), nullable=True),
        sa.Column("transmission", sa.String(length=50), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["dealers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dealer_id", "external_id", name="uq_car_listings_dealer_external_id"),
    )
    with op.batch_alter_table("car_listings", schema=None) as batch_op:
        batch_op.create_index("ix_car_listings_active", ["active"], unique=False)
        batch_op.create_index("ix_car_listings_make_model", ["make", "model"], unique=False)

    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column(
            "scraped_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["car_listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_price_snapshots_listing_id_scraped_at", ["listing_id", "scraped_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_price_snapshots_listing_id_scraped_at")

    op.drop_table("price_snapshots")
    with op.batch_alter_table("car_listings", schema=None) as batch_op:
        batch_op.drop_index("ix_car_listings_make_model")
        batch_op.drop_index("ix_car_listings_active")

    op.drop_table("car_listings")
    op.drop_table("tracked_models")
    op.drop_table("dealers")
    # ### end Alembic commands ###
